plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.chatbot'
version = '0.0.1-SNAPSHOT'
description = 'doc'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    // Spring AI 2.0 milestone 저장소
    maven { url 'https://repo.spring.io/milestone' }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:2.0.0-M4"
    }
}

dependencies {
//    implementation 'org.springframework.boot:spring-boot-starter'
//    testImplementation 'org.springframework.boot:spring-boot-starter-test'
//    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Ollama
    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'

    // pgvector
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'

    // PDF 파싱
    implementation 'org.springframework.ai:spring-ai-pdf-document-reader'

    // PostgreSQL 드라이버
    runtimeOnly 'org.postgresql:postgresql'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
