spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always # 테이블 자동 생성
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        index-type: HNSW # 수백만 건도 밀리초 단위로 검색해줌
        distance-type: COSINE_DISTANCE # 문장의 의미가 얼마나 비슷한지 하기위해
        dimensions: 768
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update       # 테이블 자동 생성/수정
    show-sql: true           # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true     # SQL 보기 좋게 출력

jwt:
  secret: doc-chatbot-jwt-secret-key-must-be-at-least-256bits-long-for-hs256
  expiration: 86400000 # 24시간 (ms)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{requestId}] %logger{36} - %msg%n"
  level:
    root: INFO
    org.chatbot.doc: DEBUG